### ISSUE TITLE
Can't fetch data

### ISSUE THREAD

**Issue by jem-computer** [javve/tictail-theme-builder#2]
Just trying to pull in my data for the first time, getting this error.

```
lib/fetcher.rb:58:in `get_store_id': undefined method `[]' for nil:NilClass (NoMethodError)
    from lib/fetcher.rb:28:in `initialize'
    from lib/fetcher.rb:165:in `new'
    from lib/fetcher.rb:165:in `<main>'
```

That line is `page.body.scan(/"id": (\d*), "vat_number"/)[0][0]` - I think the DOM has changed or something because that isn't returning any content.

**Comment by sebastianberns** [comment]
Same problem here, but I figured out a manual workaround.

**First**, you need to find your store’s id.
Go to you shop’s dashboard and open the source code. Towards the bottom of the page you’ll find 

```
<script>
var ClientSession = { … 
```

The variable `id` right after `vat_number` is your store id. 

**Next**, replace line 56 of lib/fetcher.rb to return the store id you just looked up manually.

```
def get_store_id(page)
  return "{your_store_id}"
end
```

**Then**, try running the script again— it should successfully download you store’s data.

**Comment by javve** [comment]
It should work now thanks to #4 :beers:
